- type: "rename"
  description: "Rename all files that match pattern"
  action: "rename"
  tags:
    - "rename"
  args:
    regex: "^.*\\.txt$"
    replacement: "renamed.txt"
    recursive: true
    force: true
    ignore:
      - ".(git|svn)"
- type: "write"
  tags:
    - "write"
  description: "Write a file"
  action: "write"
  args:
    path: "./test.txt"
    content: "Hello world"
    regex: "^.*\\.txt$"
    recursive: true
    force: true
- type: "delete"
  tags:
    - "delete"
  description: "Delete a file"
  action: "delete"
  args:
    recursive: true
    glob: "../[dD]ocker*"
    force: true
    ignore:
      - "([fF]ile)*"
- type: "copy"
  tags:
    - "copy"
  description: "Copy a file"
  action: "copy"
  args:
    source: "./test.txt"
    destination: "./test_copy.txt"
    action_meta: "./test_copy.txt"
    recursive: true
    force: true
- type: "move"
  tags:
    - "move"
  description: "Move a file"
  action: "move"
  args:
    source: "./test.txt"
    destination: "./test_move.txt"
    action_meta: "./test_move.txt"
    recursive: true
    force: true
